coordenadas= (10, 20, 30)
dias= ("Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sabado", "Domingo")

print("-----------------------------------------")
print("As coordenadas são:", coordenadas)
print("-----------------------------------------")
print("Os finais de semana são:", dias[5], "e", dias[6])
print("-----------------------------------------")
print("O tamanho da tupla é:", len(dias))
print("-----------------------------------------")
print("Tem 'Sabado' na tupla?", "Sabado" in dias)
print("-----------------------------------------")
print("Contagem de 'Terça' na tupla:", dias.count("Terça"))
print("-----------------------------------------")
print("Índice de 'Quarta' na tupla:", dias.index("Quarta"))
print("-----------------------------------------")